[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools-scm[simple]>=8",
    "setuptools>=80"
]

[project]
authors = [
    {email = "tim@cerazone.net", name = "Tim Cera"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules"
] # Get strings from http://pypi.python.org/pypi?%3Aaction=list_classifiers
dependencies = [
    "cltoolbox >= 1.0.0",
    "dateparser",
    "numpy",
    "pandas[excel]",
    "pint!=0.21.*",
    "pint-pandas",
    "pint<0.22; python_version < '3.9'",
    "plottoolbox >= 105.0.1",
    "pydantic >= 2.0.0",
    "scikit-learn",
    "scipy",
    "statsmodels",
    "tabulate"
]
description = "Command line script and Python library to manipulate time series."
dynamic = ["readme", "version"]
keywords = [
    "aggregate",
    "cli-app",
    "fill",
    "filter",
    "time-series"
]
license = {text = "BSD-3-Clause"}
name = "tstoolbox"
readme = "README.rst"
requires-python = ">=3.10"

[project.scripts]
tstoolbox = "tstoolbox.tstoolbox:main"

[project.urls]
bitbucket = "https://bitbucket.org/timcera/tstoolbox/src/main/"
documentation = "https://timcera.bitbucket.io/tstoolbox/docs/index.html#tstoolbox-documentation"
github = "https://github.com/timcera/tstoolbox"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
update_changelog_on_bump = true
version = "108.2.1"
version_files = ["VERSION"]

[tool.isort]
profile = "black"

[tool.jupytext]
formats = "auto:percent"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools]
include-package-data = true
license-files = ["LICENSE.txt"]

[tool.setuptools.dynamic]
readme = {file = "README.rst"}
version = {file = "VERSION"}

[tool.setuptools.packages.find]
where = ["src"]
