"""Collection of functions for the manipulation of time series."""

from tstoolbox.functions.accumulate import accumulate
from tstoolbox.functions.add_trend import add_trend
from tstoolbox.functions.aggregate import aggregate
from tstoolbox.functions.calculate_fdc import calculate_fdc
from tstoolbox.functions.calculate_kde import calculate_kde
from tstoolbox.functions.clip import clip
from tstoolbox.functions.convert import convert
from tstoolbox.functions.convert_index import convert_index
from tstoolbox.functions.convert_index_to_julian import convert_index_to_julian
from tstoolbox.functions.converttz import converttz
from tstoolbox.functions.correlation import correlation
from tstoolbox.functions.createts import createts
from tstoolbox.functions.date_offset import date_offset
from tstoolbox.functions.date_slice import date_slice
from tstoolbox.functions.describe import describe
from tstoolbox.functions.dtw import dtw
from tstoolbox.functions.equation import equation
from tstoolbox.functions.ewm_window import ewm_window
from tstoolbox.functions.expanding_window import expanding_window
from tstoolbox.functions.fill import fill
from tstoolbox.functions.filter import filter
from tstoolbox.functions.fit import fit
from tstoolbox.functions.forecast import forecast
from tstoolbox.functions.gof import gof
from tstoolbox.functions.lag import lag
from tstoolbox.functions.normalization import normalization
from tstoolbox.functions.pca import pca
from tstoolbox.functions.pct_change import pct_change
from tstoolbox.functions.peak_detection import peak_detection
from tstoolbox.functions.pick import pick
from tstoolbox.functions.plot import plot
from tstoolbox.functions.rank import rank
from tstoolbox.functions.read import read
from tstoolbox.functions.regression import regression
from tstoolbox.functions.remove_trend import remove_trend
from tstoolbox.functions.replace import replace
from tstoolbox.functions.rolling_window import rolling_window
from tstoolbox.functions.stack import stack
from tstoolbox.functions.stdtozrxp import stdtozrxp
from tstoolbox.functions.tstopickle import tstopickle
from tstoolbox.functions.unstack import unstack
